# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: handshake.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import storage_pb2 as storage__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='handshake.proto',
  package='asterales',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0fhandshake.proto\x12\tasterales\x1a\rstorage.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"R\n\x0c\x41\x64\x64\x43ommunity\x12\x11\n\tanchor_id\x18\x01 \x01(\x03\x12\x18\n\x10\x61nchor_signature\x18\x02 \x01(\x0c\x12\x15\n\rnew_community\x18\x03 \x01(\x0c\"3\n\x07\x41\x64\x64User\x12\x16\n\x0ehome_signature\x18\x01 \x01(\x0c\x12\x10\n\x08new_user\x18\x02 \x01(\x0c\"\xa3\x03\n\x08\x45xchange\x12\x1a\n\x12receiver_signature\x18\x01 \x01(\x0c\x12\x18\n\x10partial_exchange\x18\x02 \x01(\x0c\x1a\xa4\x01\n\x07Partial\x12\x18\n\x10sender_signature\x18\x01 \x01(\x0c\x12\x15\n\rcore_exchange\x18\x02 \x01(\x0c\x12\x33\n+receiver_previous_valid_sequence_number_lsb\x18\x03 \x01(\x04\x12\x33\n+receiver_previous_valid_sequence_number_msb\x18\x04 \x01(\x04\x1a\xb9\x01\n\x04\x43ore\x12\x11\n\tsender_id\x18\x01 \x01(\x03\x12\x13\n\x0breceiver_id\x18\x02 \x01(\x03\x12$\n\x1creceiver_sequence_number_lsb\x18\x03 \x01(\x04\x12$\n\x1creceiver_sequence_number_msb\x18\x04 \x01(\x04\x12\x0e\n\x06\x61mount\x18\x05 \x01(\x03\x12-\n\x08\x63urrency\x18\x06 \x01(\x0e\x32\x1b.asterales.storage.Currencyb\x06proto3')
  ,
  dependencies=[storage__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_ADDCOMMUNITY = _descriptor.Descriptor(
  name='AddCommunity',
  full_name='asterales.AddCommunity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='anchor_id', full_name='asterales.AddCommunity.anchor_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='anchor_signature', full_name='asterales.AddCommunity.anchor_signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_community', full_name='asterales.AddCommunity.new_community', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=160,
)


_ADDUSER = _descriptor.Descriptor(
  name='AddUser',
  full_name='asterales.AddUser',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='home_signature', full_name='asterales.AddUser.home_signature', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_user', full_name='asterales.AddUser.new_user', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=213,
)


_EXCHANGE_PARTIAL = _descriptor.Descriptor(
  name='Partial',
  full_name='asterales.Exchange.Partial',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender_signature', full_name='asterales.Exchange.Partial.sender_signature', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='core_exchange', full_name='asterales.Exchange.Partial.core_exchange', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver_previous_valid_sequence_number_lsb', full_name='asterales.Exchange.Partial.receiver_previous_valid_sequence_number_lsb', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver_previous_valid_sequence_number_msb', full_name='asterales.Exchange.Partial.receiver_previous_valid_sequence_number_msb', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=447,
)

_EXCHANGE_CORE = _descriptor.Descriptor(
  name='Core',
  full_name='asterales.Exchange.Core',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender_id', full_name='asterales.Exchange.Core.sender_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver_id', full_name='asterales.Exchange.Core.receiver_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver_sequence_number_lsb', full_name='asterales.Exchange.Core.receiver_sequence_number_lsb', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver_sequence_number_msb', full_name='asterales.Exchange.Core.receiver_sequence_number_msb', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='asterales.Exchange.Core.amount', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currency', full_name='asterales.Exchange.Core.currency', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=450,
  serialized_end=635,
)

_EXCHANGE = _descriptor.Descriptor(
  name='Exchange',
  full_name='asterales.Exchange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='receiver_signature', full_name='asterales.Exchange.receiver_signature', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='partial_exchange', full_name='asterales.Exchange.partial_exchange', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_EXCHANGE_PARTIAL, _EXCHANGE_CORE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=635,
)

_EXCHANGE_PARTIAL.containing_type = _EXCHANGE
_EXCHANGE_CORE.fields_by_name['currency'].enum_type = storage__pb2._CURRENCY
_EXCHANGE_CORE.containing_type = _EXCHANGE
DESCRIPTOR.message_types_by_name['AddCommunity'] = _ADDCOMMUNITY
DESCRIPTOR.message_types_by_name['AddUser'] = _ADDUSER
DESCRIPTOR.message_types_by_name['Exchange'] = _EXCHANGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddCommunity = _reflection.GeneratedProtocolMessageType('AddCommunity', (_message.Message,), dict(
  DESCRIPTOR = _ADDCOMMUNITY,
  __module__ = 'handshake_pb2'
  # @@protoc_insertion_point(class_scope:asterales.AddCommunity)
  ))
_sym_db.RegisterMessage(AddCommunity)

AddUser = _reflection.GeneratedProtocolMessageType('AddUser', (_message.Message,), dict(
  DESCRIPTOR = _ADDUSER,
  __module__ = 'handshake_pb2'
  # @@protoc_insertion_point(class_scope:asterales.AddUser)
  ))
_sym_db.RegisterMessage(AddUser)

Exchange = _reflection.GeneratedProtocolMessageType('Exchange', (_message.Message,), dict(

  Partial = _reflection.GeneratedProtocolMessageType('Partial', (_message.Message,), dict(
    DESCRIPTOR = _EXCHANGE_PARTIAL,
    __module__ = 'handshake_pb2'
    # @@protoc_insertion_point(class_scope:asterales.Exchange.Partial)
    ))
  ,

  Core = _reflection.GeneratedProtocolMessageType('Core', (_message.Message,), dict(
    DESCRIPTOR = _EXCHANGE_CORE,
    __module__ = 'handshake_pb2'
    # @@protoc_insertion_point(class_scope:asterales.Exchange.Core)
    ))
  ,
  DESCRIPTOR = _EXCHANGE,
  __module__ = 'handshake_pb2'
  # @@protoc_insertion_point(class_scope:asterales.Exchange)
  ))
_sym_db.RegisterMessage(Exchange)
_sym_db.RegisterMessage(Exchange.Partial)
_sym_db.RegisterMessage(Exchange.Core)


# @@protoc_insertion_point(module_scope)
